// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataStruct.proto

package com.codesky.reb.message.struct;

public final class DataStructOuterClass {
  private DataStructOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataStructOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.codesky.reb.message.struct.DataStruct)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 length = 1;</code>
     * @return The length.
     */
    int getLength();

    /**
     * <code>uint64 cmd = 2;</code>
     * @return The cmd.
     */
    long getCmd();

    /**
     * <code>uint64 flags = 3;</code>
     * @return The flags.
     */
    long getFlags();

    /**
     * <code>uint64 sign = 4;</code>
     * @return The sign.
     */
    long getSign();

    /**
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.codesky.reb.message.struct.DataStruct}
   */
  public static final class DataStruct extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.codesky.reb.message.struct.DataStruct)
      DataStructOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataStruct.newBuilder() to construct.
    private DataStruct(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataStruct() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataStruct();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataStruct(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              length_ = input.readUInt32();
              break;
            }
            case 16: {

              cmd_ = input.readUInt64();
              break;
            }
            case 24: {

              flags_ = input.readUInt64();
              break;
            }
            case 32: {

              sign_ = input.readUInt64();
              break;
            }
            case 42: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codesky.reb.message.struct.DataStructOuterClass.internal_static_com_codesky_reb_message_struct_DataStruct_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codesky.reb.message.struct.DataStructOuterClass.internal_static_com_codesky_reb_message_struct_DataStruct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codesky.reb.message.struct.DataStructOuterClass.DataStruct.class, com.codesky.reb.message.struct.DataStructOuterClass.DataStruct.Builder.class);
    }

    public static final int LENGTH_FIELD_NUMBER = 1;
    private int length_;
    /**
     * <code>uint32 length = 1;</code>
     * @return The length.
     */
    @java.lang.Override
    public int getLength() {
      return length_;
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private long cmd_;
    /**
     * <code>uint64 cmd = 2;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public long getCmd() {
      return cmd_;
    }

    public static final int FLAGS_FIELD_NUMBER = 3;
    private long flags_;
    /**
     * <code>uint64 flags = 3;</code>
     * @return The flags.
     */
    @java.lang.Override
    public long getFlags() {
      return flags_;
    }

    public static final int SIGN_FIELD_NUMBER = 4;
    private long sign_;
    /**
     * <code>uint64 sign = 4;</code>
     * @return The sign.
     */
    @java.lang.Override
    public long getSign() {
      return sign_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (length_ != 0) {
        output.writeUInt32(1, length_);
      }
      if (cmd_ != 0L) {
        output.writeUInt64(2, cmd_);
      }
      if (flags_ != 0L) {
        output.writeUInt64(3, flags_);
      }
      if (sign_ != 0L) {
        output.writeUInt64(4, sign_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(5, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (length_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, length_);
      }
      if (cmd_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, cmd_);
      }
      if (flags_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, flags_);
      }
      if (sign_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, sign_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.codesky.reb.message.struct.DataStructOuterClass.DataStruct)) {
        return super.equals(obj);
      }
      com.codesky.reb.message.struct.DataStructOuterClass.DataStruct other = (com.codesky.reb.message.struct.DataStructOuterClass.DataStruct) obj;

      if (getLength()
          != other.getLength()) return false;
      if (getCmd()
          != other.getCmd()) return false;
      if (getFlags()
          != other.getFlags()) return false;
      if (getSign()
          != other.getSign()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @SuppressWarnings("unchecked")
	@java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCmd());
      hash = (37 * hash) + FLAGS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFlags());
      hash = (37 * hash) + SIGN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSign());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.codesky.reb.message.struct.DataStructOuterClass.DataStruct prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.codesky.reb.message.struct.DataStruct}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.codesky.reb.message.struct.DataStruct)
        com.codesky.reb.message.struct.DataStructOuterClass.DataStructOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.codesky.reb.message.struct.DataStructOuterClass.internal_static_com_codesky_reb_message_struct_DataStruct_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.codesky.reb.message.struct.DataStructOuterClass.internal_static_com_codesky_reb_message_struct_DataStruct_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.codesky.reb.message.struct.DataStructOuterClass.DataStruct.class, com.codesky.reb.message.struct.DataStructOuterClass.DataStruct.Builder.class);
      }

      // Construct using com.codesky.reb.message.struct.DataStructOuterClass.DataStruct.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        length_ = 0;

        cmd_ = 0L;

        flags_ = 0L;

        sign_ = 0L;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.codesky.reb.message.struct.DataStructOuterClass.internal_static_com_codesky_reb_message_struct_DataStruct_descriptor;
      }

      @java.lang.Override
      public com.codesky.reb.message.struct.DataStructOuterClass.DataStruct getDefaultInstanceForType() {
        return com.codesky.reb.message.struct.DataStructOuterClass.DataStruct.getDefaultInstance();
      }

      @java.lang.Override
      public com.codesky.reb.message.struct.DataStructOuterClass.DataStruct build() {
        com.codesky.reb.message.struct.DataStructOuterClass.DataStruct result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.codesky.reb.message.struct.DataStructOuterClass.DataStruct buildPartial() {
        com.codesky.reb.message.struct.DataStructOuterClass.DataStruct result = new com.codesky.reb.message.struct.DataStructOuterClass.DataStruct(this);
        result.length_ = length_;
        result.cmd_ = cmd_;
        result.flags_ = flags_;
        result.sign_ = sign_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.codesky.reb.message.struct.DataStructOuterClass.DataStruct) {
          return mergeFrom((com.codesky.reb.message.struct.DataStructOuterClass.DataStruct)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.codesky.reb.message.struct.DataStructOuterClass.DataStruct other) {
        if (other == com.codesky.reb.message.struct.DataStructOuterClass.DataStruct.getDefaultInstance()) return this;
        if (other.getLength() != 0) {
          setLength(other.getLength());
        }
        if (other.getCmd() != 0L) {
          setCmd(other.getCmd());
        }
        if (other.getFlags() != 0L) {
          setFlags(other.getFlags());
        }
        if (other.getSign() != 0L) {
          setSign(other.getSign());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.codesky.reb.message.struct.DataStructOuterClass.DataStruct parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.codesky.reb.message.struct.DataStructOuterClass.DataStruct) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int length_ ;
      /**
       * <code>uint32 length = 1;</code>
       * @return The length.
       */
      @java.lang.Override
      public int getLength() {
        return length_;
      }
      /**
       * <code>uint32 length = 1;</code>
       * @param value The length to set.
       * @return This builder for chaining.
       */
      public Builder setLength(int value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 length = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLength() {
        
        length_ = 0;
        onChanged();
        return this;
      }

      private long cmd_ ;
      /**
       * <code>uint64 cmd = 2;</code>
       * @return The cmd.
       */
      @java.lang.Override
      public long getCmd() {
        return cmd_;
      }
      /**
       * <code>uint64 cmd = 2;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(long value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 cmd = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = 0L;
        onChanged();
        return this;
      }

      private long flags_ ;
      /**
       * <code>uint64 flags = 3;</code>
       * @return The flags.
       */
      @java.lang.Override
      public long getFlags() {
        return flags_;
      }
      /**
       * <code>uint64 flags = 3;</code>
       * @param value The flags to set.
       * @return This builder for chaining.
       */
      public Builder setFlags(long value) {
        
        flags_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 flags = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlags() {
        
        flags_ = 0L;
        onChanged();
        return this;
      }

      private long sign_ ;
      /**
       * <code>uint64 sign = 4;</code>
       * @return The sign.
       */
      @java.lang.Override
      public long getSign() {
        return sign_;
      }
      /**
       * <code>uint64 sign = 4;</code>
       * @param value The sign to set.
       * @return This builder for chaining.
       */
      public Builder setSign(long value) {
        
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 sign = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSign() {
        
        sign_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 5;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.codesky.reb.message.struct.DataStruct)
    }

    // @@protoc_insertion_point(class_scope:com.codesky.reb.message.struct.DataStruct)
    private static final com.codesky.reb.message.struct.DataStructOuterClass.DataStruct DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.codesky.reb.message.struct.DataStructOuterClass.DataStruct();
    }

    public static com.codesky.reb.message.struct.DataStructOuterClass.DataStruct getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataStruct>
        PARSER = new com.google.protobuf.AbstractParser<DataStruct>() {
      @java.lang.Override
      public DataStruct parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataStruct(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataStruct> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataStruct> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.codesky.reb.message.struct.DataStructOuterClass.DataStruct getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_codesky_reb_message_struct_DataStruct_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_codesky_reb_message_struct_DataStruct_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020DataStruct.proto\022\036com.codesky.reb.mess" +
      "age.struct\"T\n\nDataStruct\022\016\n\006length\030\001 \001(\r" +
      "\022\013\n\003cmd\030\002 \001(\004\022\r\n\005flags\030\003 \001(\004\022\014\n\004sign\030\004 \001" +
      "(\004\022\014\n\004data\030\005 \001(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_codesky_reb_message_struct_DataStruct_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_codesky_reb_message_struct_DataStruct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_codesky_reb_message_struct_DataStruct_descriptor,
        new java.lang.String[] { "Length", "Cmd", "Flags", "Sign", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
