
protos: {
   descriptors: [
      {
         cmd: 0x100000,
         fullName: 'com.codesky.test.reb.message.TestHelloMessage',
         handler: 'com.codesky.test.reb.message.TestHelloMessageHandler.hello',
      }
   ]
}